name: CI

on: [pull_request, push]

jobs:
  test:
    name: Test Erlang ${{ matrix.erlang }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        erlang: [26, 27, 28]
        os: [ubuntu-latest, windows-latest]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: rebar3 compile

      - name: Dialyzer
        run: rebar3 dialyzer

      - name: Test
        run: rebar3 eunit
